[package]
name = "rust_os"
version = "0.1.0"
author = "Staninna"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.22"
